### PR TITLE
feat: implement integration tests

### PR DESCRIPTION
**Pull request by arein**
# Description

Scaffolds the integration tests. Not actually really testing anything yet. Will do so in follow up PRs.
Will add to CD flow in follow up as well.

Towards #13 

## How Has This Been Tested?

Ran locally

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by HarryET — CHANGES_REQUESTED** [review]
Can we move all the JS stuff into the integration folder?

**Comment by arein** [comment]
> Can we move all the JS stuff into the integration folder?

done except for `package.json`

**Review by xav — APPROVED** [review]
Don't we want the integration tests to run in the CI too?

**Comment by HarryET** [comment]
There is a space for them between staging and prod, we should also have a line there that waits for the new version to be deployed though (max wait of 5mins)

**Comment by arein** [comment]
> Don't we want the integration tests to run in the CI too?

From the PR description `Will add to CD flow in follow up as well`. In CI we have functional tests.

**Pull request merged**
