### PR TITLE
feat: authenticate JWTs for tenant endpoints

### LINKED ISSUE #121: feat: Authentication on Tenant endpoints
After #120, we should add authentication to the tenant endpoints, it should validate:
- The provided token is valid
- The provided token owns the project

The first can be done using the JWT secret and the second may require changes to the internal api to expose the owner's UUID to compare to the token.

### PR DESCRIPTION
**Pull request by HarryET**
# Description
Resolves #121 

## Requirements
- [x] https://github.com/WalletConnect/explorer-api/pull/106
- [x] https://github.com/WalletConnect/cerberus/pull/7
- [x] https://github.com/WalletConnect/cloud-app/pull/364

## How Has This Been Tested?
Needs to be tested with cloud app

## Due Diligence

* [x] Breaking change
    JWT already sent but is technically breaking
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Comment by HarryET** [comment]
🚨 **Reminder:** Set JWT Secret as GitHub secret before merging `JWT_SECRET`

**Comment by HarryET** [comment]
@Cali93, just confirming the Cloud App sends the auth header on requests to the Tenants API endpoints

**Review by arein — COMMENTED** [review]
What's the migration story?

Is this breaking existing customers?

Do you have proper logs in place for when JWT validation fails to attribute projects and SDKs?

**Comment by Cali93** [comment]
> @Cali93, just confirming the Cloud App sends the auth header on requests to the Tenants API endpoints

Yes it does, this is how the header looks like:
`Authorization: Bearer access_token`

**Comment by HarryET** [comment]
> What's the migration story?

No migration should be needed as long as cloud is already sending the JWT

> Is this breaking existing customers?

See above.

> Do you have proper logs in place for when JWT validation fails to attribute projects and SDKs?

I'm going to add them before merging! And also ensure It is using the `Bearer` prefix

**Comment by HarryET** [comment]
Bearer prefix is now stripped and we have logs to show when an error is returned but I'm going to add extra logs into this now

**Comment by HarryET** [comment]
@Cali93 Just tested with cloud-app locally and it looks like the token is just sent in the body. ~~Could you make sure it's sent as a header with the `Bearer ` prefix?~~ See: https://github.com/WalletConnect/cloud-app/pull/364

**Comment by arein** [comment]
> No migration should be needed as long as cloud is already sending the JWT

I'm confused. End-users' wallets are calling this endpoint. Before, no JWT verification was in place. So most wallets are not sending it?

**Comment by HarryET** [comment]
This is only for the tenancy endpoints, the ones called by wallets already have the auth added as "optional". Tenancy endpoints are only called by the cloud-app to provision new tenants for projects

**Review by arein — APPROVED** [review]
LGTM! But how is this tested?

**Pull request merged**
