### PR TITLE
feat(ci): use larger runners in CI

### PR DESCRIPTION
**Pull request by arein**
# Description

Using the recently released hosted runners feature and a 16core/64gb ram runner config. In my tests test/publish steps now only take 50% of the time.

## How Has This Been Tested?

Tested in other repos

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Comment by HarryET** [comment]
Please check that the runner group exists as the CI/CD checks here have been waiting for 7 hrs...

**Comment by arein** [comment]
It does. Using it in the relay

**Comment by HarryET** [comment]
Screenshot 2022-11-21 at 19 02 59

**Review by HarryET — APPROVED** [review]
Working in other repos, should work here 🤞🏻

**Pull request merged**
