### PR TITLE
feat: `project_id` validation

### LINKED ISSUE #120: feat: Validate `tenant_id` is a valid `project_id` using Internal API
Check `tenant_id` is a valid `project_id` and reject when it is not valid. This can be done using the [cerberus crate](https://github.com/WalletConnect/cerberus). This is a pre-requisite for the Supabase JWT auth for the Tenant management endpoints

### PR DESCRIPTION
**Pull request by HarryET**
# Description
Resolves #120 

## How Has This Been Tested?
Locally tested.

## Due Diligence

* [x] Breaking change
    Now requires valid ids this should already be the case but is technically breaking
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Comment by HarryET** [comment]
How should the API Key be managed?
\cc @xav @arein (security)

**Review by arein — APPROVED** [review]
Nice! So Rainbow just doesn't use the `Cloud` feature?

**Comment by HarryET** [comment]
> Nice! So Rainbow just doesn't use the `Cloud` feature?

Yup, they can also remove the multi-tenant stuff all together! A few things are feature flagged now to help people with self-hosting.

**Comment by arein** [comment]
> How should the API Key be managed? \cc @xav @arein (security)

API keys are hardcoded in the Cloud App currently. Ideally you hardcode a new one just for echo else use the existing one (1Password)

**Comment by HarryET** [comment]
> > How should the API Key be managed? \cc @xav @arein (security)
> 
> API keys are hardcoded in the Cloud App currently. Ideally you hardcode a new one just for echo else use the existing one (1Password)

Okay, should I add it as a GH Actions Secret then pass it as a TF Secret Variable?

**Pull request merged**
